---
- name: Install Clickhouse
  hosts: clickhouse

  handlers:

    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: started
        enabled: yes

  tasks:

    - name: Install GPG-key for Clickhouse
      become: true
      ansible.builtin.rpm_key:
        state: present
        key: https://repo.clickhouse.com/CLICKHOUSE-KEY.GPG

    - name: Check if Clickhouse repo already exists
      ansible.builtin.stat:
        path: /etc/yum.repos.d/clickhouse.repo
      register: clickrepo

    - name: Configure Clickhouse-repo
      block:
        - name: Add Clickhouse repo (if not exists yet)
          ansible.builtin.command: "dnf config-manager --add-repo https://packages.clickhouse.com/rpm/clickhouse.repo"

        - name: Disable clickhouse-stable repo (to avoid unintentional updates to new versions due system update)
          ansible.builtin.command: "dnf config-manager --disable clickhouse-stable"
      when: not clickrepo.stat.exists
      become: true

    - name: Install clickhouse packages
      become: true
      ansible.builtin.dnf:
        enablerepo: clickhouse-stable
        name: "{{ item }}-{{ clickhouse_version }}"
        state: present
      with_items: "{{ clickhouse_packages }}"
      notify: Start clickhouse service

    - name: Start clickhouse service (if needed)
      ansible.builtin.meta: flush_handlers

    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc !=82
      changed_when: create_db.rc == 0

- name: Install Vector
  hosts: clickhouse

  handlers:

    - name: Start vector service
      become: true
      ansible.builtin.service:
        name: vector
        state: started
        enabled: yes

# Образчик редкостного бардака в репозитории vector`а:
# Все билды всех разновидностей для всех архитектур
# лежат в одном каталоге без какой-либо сортировки.
# Было бы на моих серверах - тупо выкачал бы нужный
# пакет и создал бы локальную репу.
# P.S. И, да, GPG-ключи тоже не найдены

  tasks:

    - name: Install RPMs from Vector site
      become: true
      ansible.builtin.dnf:
        name: "https://packages.timber.io/vector/{{ vector_version }}/{{ item }}-{{ vector_version }}-{{ vector_rpm_build }}.{{ vector_arch }}.rpm"
        state: present
        disable_gpg_check: true
      with_items: "{{ vector_packages }}"
      notify: Start vector service
